#!/usr/bin/env bash
#A script to tranfer files
ARG_NUM=$#
PATH_TO_PRIVATE=$4
USER_NAME=$3
SERVER_IP=$2
FILE_PATH=$1
if [ $ARG_NUM -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_PRIVATE" "$FILE_PATH" "$USER_NAME"@"$SERVER_IP":~
fi
