#!/usr/bin/env bash
# A script to install Nginx and run it and also making
# serves a simple hello world

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
