#!/usr/bin/env bash
# An explaination here
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo ps aux | grep nginx | head -n 1 | awk '{print $2}' | sudo xargs kill
