#!/usr/bin/env bash
# This script does a lot of stuff
myEnding()
{
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap myEnding SIGQUIT

(( i=1 ))
echo "$$" > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
done