#!/usr/bin/env bash
# This script is displaying the numbers from 1 to 20
# But on some numbers it displays some things after it
(( i=1 ))
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    i=$(( i=i+1 ))
done