#!/usr/bin/env bash
# This script is displaying the hours and minutes
(( HOURS=0 ))
(( MINTUES=1 ))
while [ $HOURS -le 12 ]
do
    echo "Hour: $HOURS"
    while [ $MINTUES -le 59 ]
    do
        echo "$MINTUES"
        MINTUES=$(( MINTUES+1 ))
    done
    HOURS=$(( HOURS+1 ))
    MINTUES=1
done