#!/usr/bin/env bash
# This script is displaying information about school file
myFile="school"
if test -f $myFile || test -d $myFile; then
    echo "school file exists"
    if [ ! -s "${myFile}" ] || [ ! "$(ls -A $myFile)" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$myFile" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
