#!/usr/bin/env bash
# An explination here
sed -i "s#80#8080#" /etc/nginx/sites-enabled/default
sed -i "s#www-data;#nginx;#" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
